#! /bin/sh
### BEGIN INIT INFO
# Provides:        kgp-lateinit
# Required-Start:  
# Should-Start:    opi-control
# Required-Stop:
# Default-Start:     2
# Default-Stop:      0 1
# Short-Description: Late init for control signal and LEDs
# Description: 
### END INIT INFO

# Author: PA Nilsson <pa@openproducts.se>

do_start() {
	# Acknowledge the boot msg
	idfile="/tmp/bootmsg.id"
	if [ -e $idfile ]; then
		msgid=`cat $idfile`
		kgp-notifier -a $msgid
	else
		echo "WARN: Missing id file"
	fi

}

do_stop() {
	# execution order is reversed when shutting down, so this will be
	# done early in the shutdown process
	
	kgp-notifier -l "LOG_NOTICE" -m "Shutting down" -i "sysctrl"
}

case "$1" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
