#! /bin/sh
### BEGIN INIT INFO
# Provides:        kgp-earlyinit
# Required-Start:  $local_fs
# Required-Stop: 
# Default-Start:     0 1 2
# Default-Stop:      2
# Short-Description: Early init for control signal and LEDs
# Description: 
### END INIT INFO

# Author: PA Nilsson <pa@openproducts.se>

do_start() {
	#insert the led trigger for 'timer'
	modprobe ledtrig-timer
	#insert the led trigger for 'heartbeat'
	modprobe ledtrig-heartbeat

	kgp-notifier -s  # Clean up any non-persistant messages
	
	msgid=`kgp-notifier -l "LOG_INFO" -m "Starting init scripts" -i "sysctrl"`
	if [ $? -eq 0 ]; then
		echo -n $msgid > /tmp/bootmsg.id
	fi
}

do_stop() {
	kgp-notifier -l "LOG_NOTICE" -m "Shutting down" -i "sysctrl"
}

case "$1" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
