#! /bin/bash
/bin/echo "KGP shutdown"
/usr/sbin/kgp-sysinfo -t -p | grep -q "Armada"
if [ $? -eq 0 ]; then
	# system is KEEP
	echo "Enable power down signal"
	echo "41" > /sys/class/gpio/export
	echo "high" > /sys/class/gpio/gpio41/direction
fi

